"""empty message

Revision ID: 694e32ac8b24
Revises: ed90fb11ec0a
Create Date: 2020-03-15 13:18:46.470690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694e32ac8b24'
down_revision = 'ed90fb11ec0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_analyses_parameter_set_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('credit_score_min', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('insert_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_analyses_parameter_set_version_pkey')),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'loans', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='unique')
    op.drop_table('credit_analyses_parameter_set_version')
    # ### end Alembic commands ###
